
from nltk.tokenize import RegexpTokenizer
from nltk.stem.porter import PorterStemmer
from stop_words import get_stop_words
from gensim import corpora, models
tokenizer = RegexpTokenizer(r'\w+')
stop_words = get_stop_words('en')
stemmer = PorterStemmer()
documents = [
    "Broccoli is good to eat. My brother likes to eat good broccoli, but not my mother.",
    "My mother spends a lot of time driving my brother around to baseball practice.",
    "Some health experts suggest that driving may cause increased tension and blood pressure.",
    "I often feel pressure to perform well at school, but my mother never seems to drive my brother to do better.",
    "Health professionals say that broccoli is good for your health."
]
preprocessed_documents = []
for doc in documents:
    tokens = tokenizer.tokenize(doc.lower())
    stopped_tokens = [token for token in tokens if token not in stop_words]
    stemmed_tokens = [stemmer.stem(token) for token in stopped_tokens]
    preprocessed_documents.append(stemmed_tokens)
dictionary = corpora.Dictionary(preprocessed_documents)
print("Token IDs:", dictionary.token2id)
corpus = [dictionary.doc2bow(doc) for doc in preprocessed_documents]
print("Document-Term Matrix for the first document:", corpus[0])
ldamodel = models.ldamodel.LdaModel(corpus, num_topics=2, id2word=dictionary, passes=20)
print("Topics generated by LDA:")
print(ldamodel.print_topics(num_topics=2, num_words=4)))