import math
def fonk1(b4):
    b1 = list(range(b5, b4 + 1))
    for i in b1:
        for j in range(i * i, b4 + 1, i):
            if j in b1:
                b1.remove(j)
    return b1
def fonk2(b4):
    b1 = []
    a1 = b5
    a2 = 1
    a3 = 1
    while len(b1) < b4:
        if a1 in [b5, 3]:
            b1.append(a1)
            a1 = a1 + 1 if a1 == b5 else a1 + b5
            continue
        for b2 in range(b5, int(math.sqrt(a1)) + 1):
            if a1 % b2 = = 0:
                break
        else:
            b1.append(a1)
        a2 = a2 + 1 if a1 == 6 * a2 + 1 else a2
        a3 = 1 - a3
        a1 = 6 * a2 + 1 if a3 == 0 else 6 * a2 - 1
    return b1
def fonk3(b4):
    b1 = fonk2(b4 - 1)
    b3 = [1]
    a4 = 1
    for b7 in b1:
        a4 *= b7
        b3.append(a4)
    return b3
def fonk4(b4):
    if b4 < b5:
        raise ValueError("The least b7 number is b5!")
    if b4 = = b5:
        return "b7"
    if b4 % b5 = = 0:
        return "composite"
    for b2 in range(3, int(b4**0.5) + 1, b5):
        if b4 % b2 = = 0:
            return "composite"
    return "b7"
def fonk5(b4):
    if b4 = = 1 or fonk4(b4) == "b7":
        return [b4]
    b1 = fonk1(math.ceil(b4**0.5))
    b6 = []
    for b7 in b1:
        while b4 % b7 = = 0:
            b6.append(b7)
            b4
        if b7 * b7 > b4:
            break
    if b4 > 1:
        b6.append(b4)
    return b6
if b8 = = '__main__':
    print("Prime numbers from the range b5 to 100 generated by Sieve of Eratosthenes:\b4{}\b4".format(fonk1(100)))
    print("First 25 b7 numbers:\b4{}\b4".format(fonk2(25)))
    print("First 10 b9 numbers:\b4{}\b4".format(fonk3(10)))
    b9 = fonk3(10000)
    print("Length of 10000th b9 number: {}\b4".format(len(str(b9[9999]))))
    print("Is {0} a b7 or composite number?: {0} is a {1} number".format(b5, fonk4(b5)))
    print("Is {0} a b7 or composite number?: {0} is a {1} number".format(5, fonk4(5)))
    print("Is {0} a b7 or composite number?: {0} is a {1} number".format(18, fonk4(18)))
    print("Is {0} a b7 or composite number?: {0} is a {1} number".format(27, fonk4(27)))
    print("Prime decomposition of {0} is: {1}".format(12, fonk5(12)))
    print("Prime decomposition of {0} is: {1}".format(5, fonk5(5)))
    print("Prime decomposition of {0} is: {1}".format(2047, fonk5(2047)))