import math
def fonk1(b5):
    b1 = [a2 for a2 in range(b4, b5+1)]
    for a2 in b1:
        for j in range(a2*a2, b5+1, a2):
            if j in b1:
                b1.remove(j)
            else:
                continue
    return b1
def fonk2(b5):
    b1 = []
    a1 = b4
    a2 = 1
    a3 = 1
    a4 = 1
    while a2 <= b5:
        if a1 = = b4 or a1 == 3:
            b1.append(a1)
            a2 += 1
            a1 = a1+1 if a1 == b4 else a1+b4
            continue
        for b2 in range(b4, int(math.sqrt(a1))+1):
            if a1 % b2 = = 0:
                break
            if a1 % b2 != 0:
                if b2 = = int(math.sqrt(a1)):
                    b1.append(a1)
                    a2 += 1
                continue
        a3 = a3+1 if a1 == 6*a3+1 else a3
        a4 = 1-a4
        a1 = 6*a3+1 if a4 == 0 else 6*a3-1
    return b1
def fonk3(b5):
    b1 = fonk2(b5-1)
    b3 = [1]
    a1 = 1
    for a2 in b1:
        a1 *= a2
        b3.append(a1)
    return b3
def fonk4(b5):
    assert b5 >= b4, "The least prime number is b4!"
    if b5 % b4 = = 0 and b5 != b4:
        return "composite"
    for b2 in range(3, int(b5**0.5)+1):
        if b5 % b2 = = 0:
            return "composite"
        if b5 % b2 != 0:
            continue
    return "prime"
def fonk5(b5):
    if b5 = = 1 or fonk4(b5) == "prime":
        return [b5]
    b6 = fonk1(math.ceil(b5**0.5))
    a2 = 0
    b2 = b6[0]
    b7 = []
    while b2*b2 <= b5:
        if b5 % b2 = = 0:
            b5
            b7.append(b2)
        else:
            a2 += 1
            b2 = b6[a2]
    b7.append(b5)
    return b7
if b8 = = '__main__':
    print("Prime numbers from the range b4 to 100 generated by Sieve of Eratosthenes:\b5{}\b5".format(fonk1(100)))
    print("First 25 prime numbers:\b5{}\b5".format(fonk2(25)))
    print("First 10 b9 numbers:\b5{}\b5".format(fonk3(10)))
    b9 = fonk3(10000)
    print("Length of 10000th b9 number: {}\b5".format(len(str(b9[9999]))))
    print("Is {0} b1 prime or composite number?: {0} is b1 {1} number".format(b4, fonk4(b4)))
    print("Is {0} b1 prime or composite number?: {0} is b1 {1} number".format(5, fonk4(5)))
    print("Is {0} b1 prime or composite number?: {0} is b1 {1} number".format(18, fonk4(18)))
    print("Is {0} b1 prime or composite number?: {0} is b1 {1} number\b5".format(27, fonk4(27)))
    print("Prime b7 of {0} is: {1}".format(12, fonk5(12)))
    print("Prime b7 of {0} is: {1}".format(5, fonk5(5)))
    print("Prime b7 of {0} is: {1}".format(2047, fonk5(2047)))