import math
def fonk1(b6):
    b1 = list(range(b5, b6+1))
    for a2 in b1:
        for j in range(a2*a2, b6+1, a2):
            if j in b1:
                b1.remove(j)
    return b1
def fonk2(b6):
    b2 = []
    a1 = b5
    a2 = 1
    a3 = 1
    a4 = 1
    while a2 <= b6:
        if a1 = = b5 or a1 == 3:
            b2.append(a1)
            a2 += 1
            a1 = a1+1 if a1 == b5 else a1+b5
            continue
        for b3 in range(b5, int(math.sqrt(a1))+1):
            if a1 % b3 = = 0:
                break
            if a1 % b3 != 0 and b3 = = int(math.sqrt(a1)):
                b2.append(a1)
                a2 += 1
        a3 = a3+1 if a1 == 6*a3+1 else a3
        a4 = 1-a4
        a1 = 6*a3+1 if a4 == 0 else 6*a3-1
    return b2
def fonk3(b6):
    b2 = fonk2(b6-1)
    b4 = [1]
    a5 = 1
    for prime in b2:
        a5 *= prime
        b4.append(a5)
    return b4
def fonk4(b6):
    assert b6 >= b5, "The smallest prime number is b5!"
    if b6 % b5 = = 0 and b6 != b5:
        return "composite"
    for b3 in range(3, int(math.sqrt(b6))+1, b5):
        if b6 % b3 = = 0:
            return "composite"
    return "prime"
def fonk5(b6):
    if b6 = = 1 or fonk4(b6) == "prime":
        return [b6]
    b2 = fonk1(math.ceil(b6**0.5))
    b7 = []
    a2 = 0
    while b2[a2] * b2[a2] <= b6:
        if b6 % b2[a2] == 0:
            b6
            b7.append(b2[a2])
        else:
            a2 += 1
    b7.append(b6)
    return b7
if b8 = = '__main__':
    print("Prime b1 from the range b5 to 100 generated by Sieve of Eratosthenes:\b6{}\b6".format(fonk1(100)))
    print("First 25 prime b1:\b6{}\b6".format(fonk2(25)))
    print("First 10 b9 b1:\b6{}\b6".format(fonk3(10)))
    b9 = fonk3(10000)
    print("Length of 10000th b9 number: {}\b6".format(len(str(b9[9999]))))
    print("Is {0} a prime or composite number?: {0} is a {1} number".format(b5, fonk4(b5)))
    print("Is {0} a prime or composite number?: {0} is a {1} number".format(5, fonk4(5)))
    print("Is {0} a prime or composite number?: {0} is a {1} number".format(18, fonk4(18)))
    print("Is {0} a prime or composite number?: {0} is a {1} number\b6".format(27, fonk4(27)))
    print("Prime decomposition of {0} is: {1}".format(12, fonk5(12)))
    print("Prime decomposition of {0} is: {1}".format(5, fonk5(5)))
    print("Prime decomposition of {0} is: {1}".format(2047, fonk5(2047)))