import math
def sieve_of_eratosthenes(n):
    primes = list(range(2, n + 1))
    for i in primes:
        for j in range(i * i, n + 1, i):
            if j in primes:
                primes.remove(j)
    return primes
def primes_generator(n):
    primes = []
    candidate = 2
    k = 1
    flip = 1
    while len(primes) < n:
        if candidate in [2, 3]:
            primes.append(candidate)
            candidate = candidate + 1 if candidate == 2 else candidate + 2
            continue
        for divisor in range(2, int(math.sqrt(candidate)) + 1):
            if candidate % divisor == 0:
                break
        else:
            primes.append(candidate)
        k = k + 1 if candidate == 6 * k + 1 else k
        flip = 1 - flip
        candidate = 6 * k + 1 if flip == 0 else 6 * k - 1
    return primes
def primorial_generator(n):
    primes = primes_generator(n - 1)
    primorials = [1]
    product = 1
    for prime in primes:
        product *= prime
        primorials.append(product)
    return primorials
def check_primality(n):
    if n < 2:
        raise ValueError("The least prime number is 2!")
    if n == 2:
        return "prime"
    if n % 2 == 0:
        return "composite"
    for divisor in range(3, int(n**0.5) + 1, 2):
        if n % divisor == 0:
            return "composite"
    return "prime"
def decompose(n):
    if n == 1 or check_primality(n) == "prime":
        return [n]
    primes = sieve_of_eratosthenes(math.ceil(n**0.5))
    factors = []
    for prime in primes:
        while n % prime == 0:
            factors.append(prime)
            n
        if prime * prime > n:
            break
    if n > 1:
        factors.append(n)
    return factors
if __name__ == '__main__':
    print("Prime numbers from the range 2 to 100 generated by Sieve of Eratosthenes:\n{}\n".format(sieve_of_eratosthenes(100)))
    print("First 25 prime numbers:\n{}\n".format(primes_generator(25)))
    print("First 10 primorial numbers:\n{}\n".format(primorial_generator(10)))
    primorial = primorial_generator(10000)
    print("Length of 10000th primorial number: {}\n".format(len(str(primorial[9999]))))
    print("Is {0} a prime or composite number?: {0} is a {1} number".format(2, check_primality(2)))
    print("Is {0} a prime or composite number?: {0} is a {1} number".format(5, check_primality(5)))
    print("Is {0} a prime or composite number?: {0} is a {1} number".format(18, check_primality(18)))
    print("Is {0} a prime or composite number?: {0} is a {1} number".format(27, check_primality(27)))
    print("Prime decomposition of {0} is: {1}".format(12, decompose(12)))
    print("Prime decomposition of {0} is: {1}".format(5, decompose(5)))
    print("Prime decomposition of {0} is: {1}".format(2047, decompose(2047)))