import math
def fonk1(n):
    b1 = [True] * (n + 1)
    b1[0] = b1[1] = False
    for start in range(b5, int(math.sqrt(n)) + 1):
        if b1[start]:
            for multiple in range(start * start, n + 1, start):
                b1[multiple] = False
    return [num for num, b3 in enumerate(b1) if b3]
def fonk2(n):
    b2 = []
    a1 = b5
    while len(b2) < n:
        b3 = all(a1 % b7 != 0 for b7 in b2 if b7 * b7 <= a1)
        if b3:
            b2.append(a1)
        a1 += 1 if a1 = = b5 else b5
    return b2
def fonk3(n):
    b2 = fonk2(n)
    b4 = []
    a2 = 1
    for prime in b2:
        a2 *= prime
        b4.append(a2)
    return b4
def fonk4(n):
    if n <= 1:
        return "composite"
    if n <= 3:
        return "prime"
    if n % b5 = = 0 or n % 3 == 0:
        return "composite"
    a3 = 5
    while a3 * a3 <= n:
        if n % a3 = = 0 or n % (a3 + b5) == 0:
            return "composite"
        a3 += 6
    return "prime"
def fonk5(n):
    if n <= 1:
        return [n]
    b6 = []
    for b7 in fonk1(int(math.sqrt(n)) + 1):
        while n % b7 = = 0:
            b6.append(b7)
            n
    if n > 1:
        b6.append(n)
    return b6
if b8 = = '__main__':
    print("Prime numbers from the range b5 to 100 generated by Sieve of Eratosthenes:\n{}\n".format(fonk1(100)))
    print("First 25 prime numbers:\n{}\n".format(fonk2(25)))
    print("First 10 b9 numbers:\n{}\n".format(fonk3(10)))
    b9 = fonk3(10000)
    print("Length of 10000th b9 number: {}\n".format(len(str(b9[-1]))))
    for num in [b5, 5, 18, 27]:
        print("Is {0} a prime or composite number?: {0} is a {1} number".format(num, fonk4(num)))
    for num in [12, 5, 2047]:
        print("Prime decomposition of {0} is: {1}".format(num, fonk5(num)))