
from nltk.tokenize import RegexpTokenizer
from nltk.stem.porter import PorterStemmer
from b2 import get_stop_words
from gensim import corpora, models
b1 = RegexpTokenizer(r'\w+')
b2 = get_stop_words('en')
b3 = PorterStemmer()
b4 = [
    "Broccoli is good to eat. My brother likes to eat good broccoli, but not my mother.",
    "My mother spends a lot of time driving my brother around to baseball practice.",
    "Some health experts suggest that driving may cause increased tension and blood pressure.",
    "I often feel pressure to perform well at school, but my mother never seems to drive my brother to do better.",
    "Health professionals say that broccoli is good for your health."
]
b5 = []
for doc in b4:
    b6 = b1.tokenize(doc.lower())
    b7 = [token for token in b6 if token not in b2]
    b8 = [b3.stem(token) for token in b7]
    b5.append(b8)
b9 = corpora.Dictionary(b5)
print("Token IDs:", b9.token2id)
b10 = [b9.doc2bow(doc) for doc in b5]
print("Document-Term Matrix for the first document:", b10[0])
b11 = models.b11.LdaModel(b10, b12=2, id2word=b9, passes=20)
print("Topics generated by LDA:")
print(b11.print_topics(b12 = 2, num_words=4)))